title: GitHub blog
author: GitHub User
email: tessytreffers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Keep an eye out on my project updates!

# social links
twitter_username: TreffersTessy # DO NOT include the @ character, or else the build will fail!
github_username:  TessTreff # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
